/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Charity;

import static Charity.EmpPage.con;
import java.awt.Color;
import java.awt.geom.RoundRectangle2D;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.Month;
import java.util.HashMap;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author TestEnv
 */
public class addOrphan extends javax.swing.JFrame {
private HashMap <Integer ,String> gurd;
    /**
     * Creates new form ADD
     * @param g
     */
    public addOrphan(HashMap <Integer,String> g) {
        //setUndecorated(true);
        initComponents();
        ///setOpacity(0.7f);
        gurd=new HashMap<>(g);
        for(Integer i: g.keySet())
        gname.addItem(g.get(i));
       setLocationRelativeTo(null);
     setSize(683,585);
     
       // setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),50,80));
    }

    private addOrphan() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        FName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Female = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        health = new javax.swing.JTextField();
        gText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        gname = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        reg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        street = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        gd = new datechooser.beans.DateChooserCombo();
        bd = new datechooser.beans.DateChooserCombo();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1009, -10, -1, 550));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FName");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 70, 30));

        FName.setBackground(new java.awt.Color(204, 204, 204));
        FName.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        FName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameActionPerformed(evt);
            }
        });
        getContentPane().add(FName, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 90, 140, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MName");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 70, 30));

        MName.setBackground(new java.awt.Color(204, 204, 204));
        MName.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        MName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNameActionPerformed(evt);
            }
        });
        getContentPane().add(MName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 155, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LName");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 70, 30));

        LName.setBackground(new java.awt.Color(204, 204, 204));
        LName.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(LName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 150, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sex");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 80, 30));

        gender.add(Female);
        Female.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        Female.setText("Female");
        Female.setName("Female"); // NOI18N
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        getContentPane().add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 100, -1));

        gender.add(Male);
        Male.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        Male.setText("Male");
        Male.setName("Male"); // NOI18N
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        getContentPane().add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 80, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Birth Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 120, 30));

        jLabel10.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Health Problems");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 120, 30));

        health.setBackground(new java.awt.Color(204, 204, 204));
        health.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(health, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 400, -1));

        gText.setBackground(new java.awt.Color(204, 204, 204));
        gText.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        gText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gTextActionPerformed(evt);
            }
        });
        getContentPane().add(gText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 130, -1));

        jLabel14.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Guardian Name");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 120, 30));

        gname.setBackground(new java.awt.Color(204, 204, 204));
        gname.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        gname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnameActionPerformed(evt);
            }
        });
        getContentPane().add(gname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 140, 30));

        jLabel9.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Religion");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 90, -1));

        reg.setBackground(new java.awt.Color(204, 204, 204));
        reg.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        getContentPane().add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 130, 30));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Address-City");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 120, -1));

        city.setBackground(new java.awt.Color(204, 204, 204));
        city.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 120, 30));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Documents\\NetBeansProjects\\OrphanCharity\\OrphanCharity\\ALLPIC\\icons8-save-96.png")); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 650, 20));

        jPanel3.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 20, 550));

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 550));

        jPanel5.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 640, 20));

        jLabel13.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Address-Street");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 120, -1));

        street.setBackground(new java.awt.Color(204, 204, 204));
        street.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        getContentPane().add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 130, -1));

        jLabel15.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Join Date");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 120, 30));

        gd.setCurrentView(new datechooser.view.appearance.AppearancesList("s",
            new datechooser.view.appearance.ViewAppearance("s",
                new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 255, 255),
                    (javax.swing.border.Border)null,
                    new java.awt.Font("Serif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 153),
                    0.4f),
                new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(153, 153, 255),
                    new java.awt.Color(255, 255, 0),
                    (javax.swing.border.Border)null,
                    new java.awt.Font("Serif", java.awt.Font.BOLD, 14),
                    new java.awt.Color(0, 0, 102),
                    0.2f),
                new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(0, 0, 0),
                    new java.awt.Color(51, 255, 51),
                    (javax.swing.border.Border)null,
                    new java.awt.Font("Serif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 153),
                    0.5f),
                new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(204, 204, 204),
                    new java.awt.Color(0, 0, 102),
                    (javax.swing.border.Border)null,
                    new java.awt.Font("Serif", java.awt.Font.ITALIC, 10),
                    new java.awt.Color(0, 0, 255),
                    0.4f),
                new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 255, 255),
                    (javax.swing.border.Border)null,
                    new java.awt.Font("Serif", java.awt.Font.BOLD, 12),
                    new java.awt.Color(0, 0, 255),
                    0.4f),
                new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(255, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    (javax.swing.border.Border)null,
                    new java.awt.Font("Serif", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(255, 0, 0),
                    0.3f),
                new datechooser.view.BackRenderer( 1,
                    "/C:/Users/TestEnv/Documents/NetBeansProjects/OrphanCharity/OrphanCharity/ALLPIC/h5.png"),
                true,
                true),
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    gd.setFieldFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 18));
    getContentPane().add(gd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

    bd.setCurrentView(new datechooser.view.appearance.AppearancesList("s",
        new datechooser.view.appearance.ViewAppearance("s",
            new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 255, 255),
                (javax.swing.border.Border)null,
                new java.awt.Font("Serif", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 153),
                0.4f),
            new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(153, 153, 255),
                new java.awt.Color(255, 255, 0),
                (javax.swing.border.Border)null,
                new java.awt.Font("Serif", java.awt.Font.BOLD, 14),
                new java.awt.Color(0, 0, 102),
                0.2f),
            new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(0, 0, 0),
                new java.awt.Color(51, 255, 51),
                (javax.swing.border.Border)null,
                new java.awt.Font("Serif", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 153),
                0.5f),
            new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(204, 204, 204),
                new java.awt.Color(0, 0, 102),
                (javax.swing.border.Border)null,
                new java.awt.Font("Serif", java.awt.Font.ITALIC, 10),
                new java.awt.Color(0, 0, 255),
                0.4f),
            new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 255, 255),
                (javax.swing.border.Border)null,
                new java.awt.Font("Serif", java.awt.Font.BOLD, 12),
                new java.awt.Color(0, 0, 255),
                0.4f),
            new datechooser.view.appearance.custom.CustomCellAppearance(new java.awt.Color(255, 0, 0),
                new java.awt.Color(255, 0, 0),
                (javax.swing.border.Border)null,
                new java.awt.Font("Serif", java.awt.Font.PLAIN, 12),
                new java.awt.Color(255, 0, 0),
                0.3f),
            new datechooser.view.BackRenderer( 1,
                "/C:/Users/TestEnv/Documents/NetBeansProjects/OrphanCharity/OrphanCharity/ALLPIC/h5.png"),
            true,
            true),
        new datechooser.view.appearance.ViewAppearance("custom",
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                true,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 255),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.ButtonPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                new java.awt.Color(128, 128, 128),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(0, 0, 255),
                false,
                true,
                new datechooser.view.appearance.swing.LabelPainter()),
            new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                new java.awt.Color(0, 0, 0),
                new java.awt.Color(255, 0, 0),
                false,
                false,
                new datechooser.view.appearance.swing.ButtonPainter()),
            (datechooser.view.BackRenderer)null,
            false,
            true)));
bd.setFieldFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 18));
getContentPane().add(bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 150, -1));

jPanel6.setBackground(new java.awt.Color(255, 255, 255));

javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
jPanel6.setLayout(jPanel6Layout);
jPanel6Layout.setHorizontalGroup(
    jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 630, Short.MAX_VALUE)
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 510, Short.MAX_VALUE)
    );

    getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 630, 510));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MNameActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleActionPerformed

    private void gnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnameActionPerformed
        gText.setText(gname.getSelectedItem()+"");
    }//GEN-LAST:event_gnameActionPerformed

    private void FNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regActionPerformed

    private void gTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
       /*String s2= " Create sequence orph_counter start with 6  ";
               PreparedStatement stm2= con.prepareStatement(s2);
         stm2.execute();*/
      String [] dateb=bd.getText().split("/");
      String [] datejo =gd.getText().split("/");
           int key = 0;
          for(Integer i:gurd.keySet()){
            if( gname.getSelectedItem().equals(gurd.get(i)))
                key=i;
           }
         
             String g;
             Loginpage n=new Loginpage();
             if(Female.isSelected())
                 g="F";
             else g="M";
             String s="INSERT INTO Orphan VALUES (orph_counter.nextval,'"+FName.getText()+"','"+ MName.getText()+"','"+LName.getText()+"','"+g+"','"+
                    dateb[1]+"-"+Month.of(Integer.parseInt(dateb[0])).name()+"-"+ dateb[2]+"','"+reg.getText()+"','"+health.getText()+"','"+
                    datejo[1]+"-"+Month.of(Integer.parseInt(datejo[0])).name()+"-"+ datejo[2]+"','"+ street.getText()+"','"+city.getText()+"',"+n.idm()+","+key+")" ;
         PreparedStatement stm= con.prepareStatement(s);
         stm.execute();
         
     } catch (SQLException ex) {
          JOptionPane.showMessageDialog(this,"Please, complete all information *_* ");
        // Logger.getLogger(EmpPage.class.getName()).log(Level.SEVERE, null, ex);
     }
     FName.setText("");
     MName.setText("");
     LName.setText("");
     gname.setSelectedIndex(0);
gd.setText("");
reg.setText("");
health.setText("");
bd.setText("");
gText.setText("");
street.setText("");
city.setText("");
JOptionPane.showMessageDialog(this,"Added successfully ^_^ ");
 //}////////////
 // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         //Set the Nimbus look and feel 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addOrphan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addOrphan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addOrphan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addOrphan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addOrphan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FName;
    private javax.swing.JRadioButton Female;
    private javax.swing.JTextField LName;
    private javax.swing.JTextField MName;
    private javax.swing.JRadioButton Male;
    private datechooser.beans.DateChooserCombo bd;
    private javax.swing.JTextField city;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private javax.swing.JTextField gText;
    private datechooser.beans.DateChooserCombo gd;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JComboBox<String> gname;
    private javax.swing.JTextField health;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField reg;
    private javax.swing.JTextField street;
    // End of variables declaration//GEN-END:variables
}
