/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Charity;


/**
 *
 * @author TestEnv
 */
public class Emp extends javax.swing.JPanel{

    /**
     * Creates new form Emp
     * @param Ssn
     * @param sex
     * @param name
     * @param rel
     * @param pho
     * @param add
     * @param j
     * @param e
     * @param Sal
     */
    public Emp( int Ssn,String sex,String name, String rel, int pho,String j,String add,String e,int Sal) {
        initComponents();
        ssn.setText(Ssn+"");
          Email.setText(e);
 Name.setText(name);
    Phone.setText(pho+"");
     Reg.setText(rel);
   Salary.setText(Sal+"$");
   address.setText(add);
    jop.setText(j);
    if(sex.equalsIgnoreCase("m"))
   phote.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Documents\\NetBeansProjects\\OrphanCharity\\OrphanCharity\\ALLPIC\\m.png"));
    else if(sex.equalsIgnoreCase("f")) 
         phote.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Documents\\NetBeansProjects\\OrphanCharity\\OrphanCharity\\ALLPIC\\f.png")); // NOI18N
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phote = new javax.swing.JLabel();
        Salary = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Reg = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        jop = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        ssn = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        setLayout(null);
        add(phote);
        phote.setBounds(10, 10, 60, 60);

        Salary.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Salary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Salary.setText("1000$");
        Salary.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryActionPerformed(evt);
            }
        });
        add(Salary);
        Salary.setBounds(960, 30, 80, 30);

        Name.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name.setText("Tala Mohammed Yaseen");
        Name.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        add(Name);
        Name.setBounds(100, 30, 210, 30);

        Reg.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Reg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Reg.setText("Islam");
        Reg.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegActionPerformed(evt);
            }
        });
        add(Reg);
        Reg.setBounds(310, 30, 50, 30);

        Phone.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Phone.setText("0599730297");
        Phone.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });
        add(Phone);
        Phone.setBounds(360, 30, 110, 30);

        jop.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jop.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jop.setText("Voleenters");
        jop.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jopActionPerformed(evt);
            }
        });
        add(jop);
        jop.setBounds(480, 30, 110, 30);

        address.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address.setText("Nablus- Fisial Street");
        address.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        add(address);
        address.setBounds(590, 30, 160, 30);

        Email.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Email.setText("talamyaseen@gmail.com");
        Email.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        add(Email);
        Email.setBounds(760, 30, 210, 30);

        ssn.setEditable(false);
        ssn.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        ssn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ssn.setText("1");
        ssn.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        ssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnActionPerformed(evt);
            }
        });
        add(ssn);
        ssn.setBounds(80, 30, 30, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalaryActionPerformed

    private void RegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegActionPerformed

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed

    private void jopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jopActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void ssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseReleased

public String getEmail() {
		return Email.getText();
	}

	public String getname() {
		return Name.getText();
	}

	public String getPhone() {
		return Phone.getText();
	}

	public String getReg() {
		return Reg.getText();
	}

	public int getSalary() {
        
		return Integer.parseInt(Salary.getText().replace("$","" ));
	}

	public  String getAddress() {
		return address.getText();
	}

	public  String getJop() {
		return jop.getText();
	}
        public  int getSSN() {
		return Integer.parseInt(ssn.getText());
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Reg;
    private javax.swing.JTextField Salary;
    private javax.swing.JTextField address;
    private javax.swing.JTextField jop;
    private javax.swing.JLabel phote;
    private javax.swing.JTextField ssn;
    // End of variables declaration//GEN-END:variables
}
