/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Charity;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author TestEnv
 */
public class Loginpage extends javax.swing.JFrame {

    static String t;
    public Loginpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        email = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        presslogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Bibpic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email.setBackground(new java.awt.Color(51, 51, 51));
        email.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 600, 280, 50));

        pass.setBackground(new java.awt.Color(51, 51, 51));
        pass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 670, 280, 50));

        presslogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Documents\\NetBeansProjects\\OrphanCharity\\OrphanCharity\\ALLPIC\\log_No-removebg-preview.png")); // NOI18N
        presslogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pressloginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pressloginMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pressloginMousePressed(evt);
            }
        });
        jPanel2.add(presslogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 800, 370, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Documents\\NetBeansProjects\\OrphanCharity\\OrphanCharity\\ALLPIC\\اية2-removebg-preview (3).png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 390, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Documents\\NetBeansProjects\\OrphanCharity\\OrphanCharity\\ALLPIC\\done.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 440, 580));

        Bibpic.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Documents\\NetBeansProjects\\OrphanCharity\\OrphanCharity\\ALLPIC\\h1.png")); // NOI18N
        jPanel2.add(Bibpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 930));

        loginPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 930));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        MyThread m=new MyThread(Bibpic,1500);
        m.start();
    }//GEN-LAST:event_formWindowOpened

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void pressloginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pressloginMousePressed
        // TODO add your handling code here:
         String e;
            char p[];
            String P;
            int f=0;
        try{
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",  "C##Samaa_Yasin","654321");
            Statement stm= con.createStatement();
            ResultSet r= stm.executeQuery("SELECT EMAIL,EPASSWORD from Employee");
           
            while(r.next()){
                e=email.getText();
                t=e;
                p=pass.getPassword();
                P=String.valueOf(p);
                if(r.getString(1).equalsIgnoreCase(e)){
                    if(r.getString(2).equals(P)){
                        f=1;
                        String j;
                         try{            
                 HomePage h=new HomePage();
                 Homeemp2 h2=new Homeemp2();
                  Homeemp1 h1=new Homeemp1();
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());           
            Connection c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",  "C##Samaa_Yasin","654321");
            Statement s= c.createStatement();
           // int Pssn= Integer.valueOf(P);
            ResultSet R= s.executeQuery("SELECT JOBTYPE from Employee where EPassword='"+P+"'");

            while(R.next()){
            j=R.getString(1).trim();
            eventpanel E= new  eventpanel();
            if(j.equalsIgnoreCase("manager")){
                 E.setVisible(false);
                h1.setVisible(false);
                 h2.setVisible(false);
                  h.setVisible(true);
                        this.setVisible(false);
                        break;
            }
           else if(j.equalsIgnoreCase("ORPHAN_R")){
                      E.setVisible(false);

                    h1.setVisible(false);
                 h.setVisible(false);
                  h2.setVisible(true);
                        this.setVisible(false);
                         break;
            }
           else if(j.equalsIgnoreCase("EVENT_R")){
               E.setVisible(false);
                h.setVisible(false);
                 h2.setVisible(false);
                  h1.setVisible(true);
                        this.setVisible(false);
                         break;
            }
            
            }
           
                         }  catch (Exception ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } 
                          
                        JOptionPane.showMessageDialog(null, "Logged in successfully\nWelcome");

                        break;
                    }
                }

            }
            if(f==0){

                JOptionPane.showMessageDialog(null, "The email or password is incorrect\nMake sure you entered it correctly");

            }
        }
        catch (Exception ex){
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_pressloginMousePressed

    private void pressloginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pressloginMouseEntered
        // TODO add your handling code here:
                        presslogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Documents\\NetBeansProjects\\OrphanCharity\\OrphanCharity\\ALLPIC\\log L.png"));

    }//GEN-LAST:event_pressloginMouseEntered

    private void pressloginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pressloginMouseExited
        // TODO add your handling code here:
       presslogin.setIcon(new javax.swing.ImageIcon( "C:\\Users\\TestEnv\\Documents\\NetBeansProjects\\OrphanCharity\\OrphanCharity\\ALLPIC\\log_No-removebg-preview.png"));
    }//GEN-LAST:event_pressloginMouseExited
 public static int idm(){
     try{
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE",  "C##Samaa_Yasin","654321");
            Statement stm= con.createStatement();
            
            ResultSet r= stm.executeQuery("SELECT SSN from Employee where email ='"+t+"'");
            while(r.next()){
                int id=r.getInt(1);
                return id;
            }
     }   catch (Exception ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } 
    return 0;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bibpic;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel presslogin;
    // End of variables declaration//GEN-END:variables
}
