/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Charity;

import java.sql.Date;
import java.time.Month;


/**
 *
 * @author TestEnv
 */
public class orphpanel extends javax.swing.JPanel{

    /**
     * Creates new form Emp
     * @param Ssn
     * @param sex
     * @param name
     * @param rel
     * @param pho
     * @param add
     * @param j
     * @param e
     * @param Sal
     */
    public orphpanel( int id,String sex,String name, String rel, Date bd,String health,Date join,String add ,String gu) {
        initComponents();
        idc.setText(id+"");
          
       //   subString s=
 Name.setText(name);
   String [] d=bd.toString().split("-");
     String [] dj=join.toString().split("-");
 date.setText(d[2]+"-"+Month.of(Integer.parseInt(d[1])).name().substring(0,3)+"-"+d[0]);
datejoin.setText(dj[2]+"-"+Month.of(Integer.parseInt(dj[1])).name().substring(0,3)+"-"+dj[0]);

     Reg.setText(rel);
   address.setText(add);
    heal.setText(health);
    gname.setText(gu);
    if(sex.equalsIgnoreCase("m"))
   phote.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Documents\\NetBeansProjects\\OrphanCharity\\OrphanCharity\\ALLPIC\\m.png"));
    else if(sex.equalsIgnoreCase("f")) 
         phote.setIcon(new javax.swing.ImageIcon("C:\\Users\\TestEnv\\Documents\\NetBeansProjects\\OrphanCharity\\OrphanCharity\\ALLPIC\\f.png")); // NOI18N
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phote = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Reg = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        heal = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        datejoin = new javax.swing.JTextField();
        idc = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        phote1 = new javax.swing.JLabel();
        Name1 = new javax.swing.JTextField();
        Reg1 = new javax.swing.JTextField();
        date1 = new javax.swing.JTextField();
        heal1 = new javax.swing.JTextField();
        address1 = new javax.swing.JTextField();
        datejoin1 = new javax.swing.JTextField();
        idc1 = new javax.swing.JTextField();
        gname = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        setLayout(null);
        add(phote);
        phote.setBounds(10, 10, 60, 60);

        Name.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name.setText("Tala Mohammed Yaseen");
        Name.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        add(Name);
        Name.setBounds(100, 30, 210, 30);

        Reg.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Reg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Reg.setText("Islam");
        Reg.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegActionPerformed(evt);
            }
        });
        add(Reg);
        Reg.setBounds(310, 30, 50, 30);

        date.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date.setText("11/5/2004");
        date.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        add(date);
        date.setBounds(360, 30, 120, 30);

        heal.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        heal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        heal.setText("Cancer");
        heal.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        heal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                healActionPerformed(evt);
            }
        });
        add(heal);
        heal.setBounds(760, 30, 100, 30);

        address.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address.setText("Nablus- Fisial Street");
        address.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        add(address);
        address.setBounds(480, 30, 160, 30);

        datejoin.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        datejoin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        datejoin.setText("11/8/2000");
        datejoin.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        datejoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datejoinActionPerformed(evt);
            }
        });
        add(datejoin);
        datejoin.setBounds(650, 30, 110, 30);

        idc.setEditable(false);
        idc.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        idc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idc.setText("1");
        idc.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        idc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcActionPerformed(evt);
            }
        });
        add(idc);
        idc.setBounds(80, 30, 30, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1formMouseReleased(evt);
            }
        });
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1formPropertyChange(evt);
            }
        });
        jPanel1.setLayout(null);
        jPanel1.add(phote1);
        phote1.setBounds(10, 10, 60, 60);

        Name1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Name1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name1.setText("Tala Mohammed Yaseen");
        Name1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name1ActionPerformed(evt);
            }
        });
        jPanel1.add(Name1);
        Name1.setBounds(100, 30, 210, 30);

        Reg1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Reg1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Reg1.setText("Islam");
        Reg1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Reg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reg1ActionPerformed(evt);
            }
        });
        jPanel1.add(Reg1);
        Reg1.setBounds(330, 30, 50, 30);

        date1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        date1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date1.setText("11/5/2004");
        date1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        date1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date1ActionPerformed(evt);
            }
        });
        jPanel1.add(date1);
        date1.setBounds(420, 30, 110, 30);

        heal1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        heal1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        heal1.setText("Cancer");
        heal1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        heal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heal1ActionPerformed(evt);
            }
        });
        jPanel1.add(heal1);
        heal1.setBounds(890, 30, 100, 30);

        address1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        address1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address1.setText("Nablus- Fisial Street");
        address1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        address1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address1ActionPerformed(evt);
            }
        });
        jPanel1.add(address1);
        address1.setBounds(540, 30, 160, 30);

        datejoin1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        datejoin1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        datejoin1.setText("11/8/2000");
        datejoin1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        datejoin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datejoin1ActionPerformed(evt);
            }
        });
        jPanel1.add(datejoin1);
        datejoin1.setBounds(740, 30, 100, 30);

        idc1.setEditable(false);
        idc1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        idc1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idc1.setText("1");
        idc1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        idc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idc1ActionPerformed(evt);
            }
        });
        jPanel1.add(idc1);
        idc1.setBounds(80, 30, 30, 30);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 0);

        gname.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        gname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gname.setText("Ahmad yaseen");
        gname.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        gname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnameActionPerformed(evt);
            }
        });
        add(gname);
        gname.setBounds(870, 30, 130, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void RegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void healActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_healActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_healActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void datejoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datejoinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datejoinActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void idcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseReleased

    private void Name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name1ActionPerformed

    private void Reg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Reg1ActionPerformed

    private void date1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date1ActionPerformed

    private void heal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heal1ActionPerformed

    private void address1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address1ActionPerformed

    private void datejoin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datejoin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datejoin1ActionPerformed

    private void idc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idc1ActionPerformed

    private void jPanel1formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1formMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1formMousePressed

    private void jPanel1formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1formMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1formMouseReleased

    private void jPanel1formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1formPropertyChange

    private void gnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnameActionPerformed

public String getDatej() {
		return datejoin.getText();
	}

	public String getname() {
		return Name.getText();
	}

	public String getDateb() {
		return date.getText();
	}

	public String getReg() {
		return Reg.getText();
	}

	
	public  String getAddress() {
		return address.getText();
	}

	public  String getHealth() {
		return heal.getText();
	}
        public  int getId() {
		return Integer.parseInt(idc.getText());
	}
        public  String getGname() {
		return gname.getText();
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Name1;
    private javax.swing.JTextField Reg;
    private javax.swing.JTextField Reg1;
    private javax.swing.JTextField address;
    private javax.swing.JTextField address1;
    private javax.swing.JTextField date;
    private javax.swing.JTextField date1;
    private javax.swing.JTextField datejoin;
    private javax.swing.JTextField datejoin1;
    private javax.swing.JTextField gname;
    private javax.swing.JTextField heal;
    private javax.swing.JTextField heal1;
    private javax.swing.JTextField idc;
    private javax.swing.JTextField idc1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel phote;
    private javax.swing.JLabel phote1;
    // End of variables declaration//GEN-END:variables
}
